apiVersion: v1
kind: Service
metadata:
  name: mcp-production
  namespace: mcp-server
spec:
  selector:
    app: mcp-production
  ports:
    - protocol: TCP
      nodePort: 30000
      targetPort: 3000
      port: 30000
  type: NodePort
